version: "3.9"

networks:
  ecommerce_net:
    name: ecommerce_net
    driver: bridge

volumes:
  commerce-store:
    driver: local

services:
  database:
    image: postgres:13
    container_name: commerce
    volumes:
      - commerce-store:/var/lib/postgresql
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: store
    networks:
      - ecommerce_net