version: '3.9'

networks:
  ecommerce_net:
    name: ecommerce_net
    driver: bridge

volumes:
  commerce-store:
    driver: local

services:
  database:
    image: postgres:13
    container_name: database-ecommerce
    volumes:
      - commerce-store:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=store
    networks:
      - ecommerce_net
